=== microsoft/sarif-sdk/src/Sarif/Schemata/sarif-external-property-file-2.1.0-rtm.0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "SARIF External Property File Schema Version 2.1.0-rtm.0 JSON Schema",
  "type": "object",
  "properties": {

    "$schema": {
      "description": "The URI of the JSON schema corresponding to the version of the external property file format.",
      "type": "string",
      "format": "uri"
    },

    "version": {
      "description": "The SARIF format version of this external properties object.",
      "enum": [ "2.1.0" ]
    },

    "guid": {
      "description": "A stable, unique identifer for this external properties object, in the form of a GUID.",
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    },

    "runGuid": {
      "description": "A stable, unique identifer for the run associated with this external properties object, in the form of a GUID.",
      "type": "string",
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    },

    "conversion": {
      "description": "A conversion object that will be merged with an external run.",
      "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/conversion"
    },

    "graphs": {
      "description": "An array of graph objects that will merged with an external run.",
      "type": "array",
      "minItems": 0,
      "default": [],
      "uniqueItems": true,
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/graph"
      }
    },

    "externalizedProperties": {
      "description": "Key/value pairs that provide additional information that will be merged with an external run.",
      "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/propertyBag"
    },

    "artifacts": {
      "description": "An array of artifact objects that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/artifact"
      }
    },

    "invocations": {
      "description": "Describes the invocation of the analysis tool that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": false,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/invocation"
      }
    },

    "logicalLocations": {
      "description": "An array of logical locations such as namespaces, types or functions that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/logicalLocation"
      }
    },

    "threadFlowLocations": {
      "description": "An array of threadFlowLocation objects that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/threadFlowLocation"
      }
    },

    "results": {
      "description": "An array of result objects that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": false,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/result"
      }
    },

    "taxonomies": {
      "description": "Tool taxonomies that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/toolComponent"
      }
    },

    "driver": {
      "description": "The analysis tool object that will be merged with an external run.",
      "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/toolComponent"
    },

    "extensions": {
      "description": "Tool extensions that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/toolComponent"
      }
    },

    "policies": {
      "description": "Tool policies that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/toolComponent"
      }
    },

    "translations": {
      "description": "Tool translations that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/toolComponent"
      }
    },

    "addresses": {
      "description": "Addresses that will be merged with with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": false,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/address"
      }
    },

    "webRequests": {
      "description": "Requests that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/webRequest"
      }
    },

    "webResponses": {
      "description": "Responses that will be merged with an external run.",
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "default": [],
      "items": {
        "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/webResponse"
      }
    },

    "properties": {
      "description": "Key/value pairs that provide additional information about the external properties.",
      "$ref": "https://schemastore.azurewebsites.net/json/sarif#/definitions/propertyBag"
    }
  },
  "required": [ "version" ]
}

=== microsoft/sarif-sdk/src/Test.FunctionalTests.Sarif/TestData/Multitool/ValidateCommand/Inputs/SimpleExample.sarif-external-properties.json
{
  "$schema": "http://json.schemastore.org/sarif-external-property-file-2.1.0-rtm.1.json",
  "version": "2.1.0",

  "guid": "00001111-2222-3333-8444-555566667777",
  "runGuid": "88889999-1AAA-2BBB-BCCC-DDDDEEEEFFFF",

  "artifacts": [
    {
      "location": { "uri": "apple.png" },
      "mimeType": "image/png"
    },
    {
      "location": { "uri": "banana.png" },
      "mimeType": "image/png"
    }
  ],
  "externalizedProperties": { "team": "Security Assurance Team" }
}
